language: go
go:
  - 1.5.3
  - 1.6
install:
  - go get -t github.com/FreifunkBremen/respond-collector/...
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - ./.test-coverage
