---
respondd:
  enable: true
  collectinterval: 15
webserver:
  enable: false
  port: 8080
  address: 127.0.0.1
  webroot: webroot
  websocketnode: false
nodes:
  enable: true
  nodes_path: /var/www/html/meshviewer/data/nodes.json
  graphs_path: /var/www/html/meshviewer/data/graph.json
  saveinterval: 5
  aliases_enable: false
  aliases_path: /var/www/html/meshviewer/data/aliases.json
influxdb:
  enable: false
  host: http://localhost:8086
  database: ffhb
  username:
  password:
