---
responedd:
  enable: true
  collectinterval: 15
webserver:
  enable: false
  port: 8080
  address: 127.0.0.1
  webroot: webroot
  websocketnode: false
nodes:
  enable: true
  nodes_path: /var/www/html/meshviewer/nodes.json
  graphs_path: /var/www/html/meshviewer/graphs.json
  saveinterval: 5
  aliases_enable: false
  aliases_path: webroot/aliases.json
  vpn_addresses:
  - da:25:d6:5c:97:6f
  - da:62:f2:70:c8:8d
