---
respondd:
  enable: true
  interface: eth0

  # Collected data every n seconds
  collectinterval: 60
webserver:
  enable: false
  port: 8080
  address: 127.0.0.1
  webroot: webroot
  api:
    newnodes: true
    aliases: true
nodes:
  enable: true
  nodes_path: /var/www/html/meshviewer/data/nodes_all.json
  nodesmini_path: /var/www/html/meshviewer/data/nodes.json
  graphs_path: /var/www/html/meshviewer/data/graph.json
  aliases_enable: false
  aliases_path: /var/www/html/meshviewer/data/aliases.json

  # Export nodes and graph every n seconds
  saveinterval: 5

  # Expire offline nodes after n days
  max_age: 7

influxdb:
  enable: false
  host: http://localhost:8086
  database: ffhb
  username:
  password:
